#################
### AUTOSTART ###
#################
exec-once = hyprpaper & $polkit & hyprlock & fcitx5
# exec-once = sleep 10 && systemctl --user start opentabletdriver.service --now
exec-once = sleep 10 && otd-daemon
